image: Visual Studio 2019 Preview
install:
  - cinst fake
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: fake.exe run build.fsx --parallel 1

artifacts:
- path: \artifacts\**\*.*

deploy:
  provider: NuGet
  server: https://nuget.mazeadmin.com/api/v3/index.json
  api_key:
    secure: gg1uXcoqC9ziCVpB5LmhIB3e6U4/s2gStEnicsKWuik=
  artifact: /artifacts/.*\.nupkg/


test: off
